---
- include_tasks:
    file: nginx-cert.yml
    apply:
      tags: nginx-cert
  tags: nginx-cert

- include_tasks:
    file: nginx-vhost.yml
    apply:
      tags: nginx-vhost
  tags: nginx-vhost

- include_tasks:
    file: nginx-restart.yml
    apply:
      tags: nginx-restart
  tags: nginx-restart
